apiVersion: v1
kind: Service
metadata:
  name: {{ include "rootless-nginx.fullname" . }}
  labels:
    app: {{ include "rootless-nginx.fullname" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 3 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app: {{ include "rootless-nginx.fullname" . }}
